name: Smoke test

on:
  workflow_dispatch: # Manual trigger
  schedule: # Every sunday at 00:00
    - cron: "0 00 * * SUN"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install, Build
        run: |
          pnpm install
          pnpm build

      - name: Update ESLint to v9
        run: pnpm i -D eslint@9

      - uses: AriPerkkio/eslint-remote-tester-run-action@v5
        with:
          issue-title: "Results of weekly scheduled smoke test"
          eslint-remote-tester-config: eslint-remote-tester.config.ts
